services:
  - type: worker
    name: voo-milionario
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    envVars:
      - key: TG_BOT_TOKEN
        value: "7585234067:AAF1xfSbMCh7LOckXViD2_iUfKig7GYgwO4"
      - key: CHAT_ID
        value: "8101413562"
      - key: GRUPO_ID
        value: "-1002769928832"
      - key: GB_USERNAME
        value: "932071284"
      - key: GB_PASSWORD
        value: "932071284t"
