services:
  - type: web
    name: voo-milionario
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    plan: free
    autoDeploy: true
